# Generated by Django 3.1.6 on 2021-04-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_appointment_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Addinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('doctor_name', models.CharField(max_length=100)),
                ('specilization', models.CharField(max_length=100)),
                ('educational_qualifications', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('opd_shift', models.CharField(max_length=100)),
            ],
        ),
    ]
