# Generated by Django 3.1.6 on 2021-04-09 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=20)),
                ('educational_qualification', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.department')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shift')),
            ],
        ),
    ]
