# Generated by Django 3.1.6 on 2021-04-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_nurse_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift',
            field=models.CharField(max_length=50),
        ),
    ]
