# Generated by Django 3.1.6 on 2021-04-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210409_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
