# Generated by Django 3.1.6 on 2021-04-13 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210409_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compounder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=20)),
                ('educational_qualification', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField()),
                ('joining_date', models.DateField(null=True)),
                ('image', models.ImageField(upload_to='')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shift')),
            ],
        ),
    ]
