# Generated by Django 3.1.7 on 2021-04-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_compounder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('email', models.EmailField(max_length=40, null=True)),
                ('message', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
