# Generated by Django 3.1.6 on 2021-04-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_Number', models.IntegerField(null=True)),
                ('Patient_Id', models.IntegerField(blank=True, default='')),
                ('Nurse_Id', models.IntegerField(blank=True, default='')),
                ('Compounder_Id', models.IntegerField(blank=True, default='')),
                ('Bed_Number', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='compounder',
            name='Compounder_Id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='Nurse_Id',
            field=models.IntegerField(null=True),
        ),
    ]
