# Generated by Django 3.1.6 on 2021-04-20 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210421_0148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room_service',
            old_name='Bed_Number',
            new_name='bed_number',
        ),
        migrations.RenameField(
            model_name='room_service',
            old_name='Room_Number',
            new_name='patient_age',
        ),
        migrations.RemoveField(
            model_name='compounder',
            name='Compounder_Id',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='Nurse_Id',
        ),
        migrations.RemoveField(
            model_name='room_service',
            name='Compounder_Id',
        ),
        migrations.RemoveField(
            model_name='room_service',
            name='Nurse_Id',
        ),
        migrations.RemoveField(
            model_name='room_service',
            name='Patient_Id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='room_service',
            name='patient_gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.gender'),
        ),
        migrations.AddField(
            model_name='room_service',
            name='patient_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='room_service',
            name='room_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='room_service',
            name='staff_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
