# Generated by Django 3.1.6 on 2021-04-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210421_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compounder',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='educational_qualification',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
