# Generated by Django 3.1.6 on 2021-04-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210421_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compounder',
            name='educational_qualification',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
