# Generated by Django 3.1.6 on 2021-04-21 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210421_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compounder',
            name='educational_qualification',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='educational_qualification',
        ),
    ]
