# Generated by Django 3.1.6 on 2021-04-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210421_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='approved',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
